[build]
  # Tell Netlify your code is inside the frontend folder
  base = "frontend"
  
  # The directory where the built files will be (relative to 'frontend')
  publish = "dist"
  
  # The command to run inside the 'frontend' folder
  command = "npm run build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18"
